package org.algotithmcontestdatacollect.displaybackend.repositories.IntelligentTraining;

import org.algotithmcontestdatacollect.displaybackend.entities.IntelligentTraining.IntelligentTrainingStrategy;
import org.springframework.data.jpa.repository.JpaRepository;

public interface IntelligentTrainingStrategyRepository extends JpaRepository<IntelligentTrainingStrategy,Integer> {
}
